### ISSUE TITLE
[Feat] [Core] Define RelyingParty configuration

### ISSUE THREAD

**Issue by danielegiallonardo** [italia/spid-cie-oidc-aspnetcore#2]
Define a configuration object for a generic RelyingParty and implement its loading from settings
The RelyingParty should contains at least:

- A ClientId (sub)
- A Name
- At least one OpenId Federation signing key
- At least one OpenId Core signing key
- At least one Trust mark
- An Issuer
- At least one Contact
- At least one Redirect uri
- At least one Authority Hint

**Comment by peppelinux** [comment]
you can even use the json validation schemas available in spid-cie-oidc-django
https://github.com/italia/spid-cie-oidc-django/blob/main/spid_cie_oidc/entity/schemas/rp_metadata.py

here how to export manually the schemes
https://github.com/italia/spid-cie-oidc-django/blob/main/docs/schemas/METADATA.md

here a UI with automatic exports (we're going to make all the entries collassable in the UI)
![image](https://user-images.githubusercontent.com/1297620/157657846-bd073fa5-4244-40d9-bc18-b6585a417f6a.png)
