### ISSUE TITLE
[Feat] [Core] Implement scoped SpidCieOptions 

### ISSUE THREAD

**Issue by danielegiallonardo** [italia/spid-cie-oidc-aspnetcore#3]
Allow SpidCieOptions to change its values dynamically on a per-RP basis

**Comment by peppelinux** [comment]
see this if helps
https://github.com/italia/spid-cie-oidc-django/blob/dev/spid_cie_oidc/relying_party/settings.py#L65

here how to select dynamically a profile for a given authorization request
https://github.com/italia/spid-cie-oidc-django/blob/dev/docs/technical_specifications/RELYING_PARTY.md#authorization
