### ISSUE TITLE
[Feat] [Core] Build the buttons dynamically

### ISSUE THREAD

**Issue by danielegiallonardo** [italia/spid-cie-oidc-aspnetcore#4]
Allow the Spid and Cie buttons to be built dynamically based on the OP list retrieved by the configured FederationAuthorities

**Comment by peppelinux** [comment]
in spid-cie-oidc-django we made a CLI command that can be scheduled, that fetches all the provider for a given trust anchor (federation)

here:
https://github.com/italia/spid-cie-oidc-django/blob/dev/spid_cie_oidc/relying_party/management/commands/fetch_openid_providers.py

then in the views we applied a strategy to dynamicall update an expired trust chain (if and when needed, is not mandatory)
https://github.com/italia/spid-cie-oidc-django/blob/dev/spid_cie_oidc/relying_party/views.py#L154

then we have the final metadata as an attribute of the trust chain, here
https://github.com/italia/spid-cie-oidc-django/blob/dev/spid_cie_oidc/relying_party/views.py#L170

**Comment by peppelinux** [comment]
the buttons then are built in the view of the login page, here:
https://github.com/italia/spid-cie-oidc-django/blob/dev/spid_cie_oidc/relying_party/views.py#L580

the html template processes the trust chain objects and renders the required attributes given by the final metadata of the OPs, here:
https://github.com/italia/spid-cie-oidc-django/blob/dev/spid_cie_oidc/relying_party/templates/rp_landing.html#L61
