### ISSUE TITLE
[Feat] [OpenIdFed] Build the trust chains with the OPs

### ISSUE THREAD

**Issue by danielegiallonardo** [italia/spid-cie-oidc-aspnetcore#5]
Dynamically build, validate and cache statically the trust chains with the OPs, by retrieving the OPs list from the configured FederationAuthorities and by validating their Entity Configurations.
Manage the trust chains avoiding loops and chains expirations in the static cache

**Comment by peppelinux** [comment]
See this if helps to consolidate a unique API between many implementations.
https://github.com/italia/spid-cie-oidc-django/blob/main/spid_cie_oidc/entity/statements.py#L132

feel free to put your suggestions to improve these interfaces
